---
- hosts: oracle
  tasks:
  - name: Update all installed packages using apt module
    apt:
      name: '*'
      state: latest
      update_cache: yes
    register: apt_update_status

  - name: Remove packates not needed anymore
    apt:
      autoremove: yes

  - name: Reboot when packages were updated
    reboot:
    when: apt_update_status.changed
